export const authConstants = {
    LOGIN_REQUEST :'LOGIN_REQUEST',
    LOGIN_FAILURE : 'LOGIN_FAILURE',
    LOGIN_SUCCESS : 'LOGIN_SUCCESS',
    LOGOUT_REQUEST :'LOGOUT_REQUEST',
    LOGOUT_FAILURE : 'LOGOUT_FAILURE',
    LOGOUT_SUCCESS : 'LOGOUT_SUCCESS'
}

export const userConstants = {
   USER_REGISTER_REQUEST :'USER_REGISTER_REQUEST',
   USER_REGISTER_FAILURE : 'USER_REGISTER_FAILURE',
   USER_REGISTER_SUCCESS : 'USER_REGISTER_SUCCESS'
}


export const categoryConstants = {
    GET_ALL_CATEGORY_REQUEST :'GET_ALL_CATEGORY_REQUEST',
    GET_ALL_CATEGORY_FAILURE : 'GET_ALL_CATEGORY_FAILURE',
    GET_ALL_CATEGORY_SUCCESS : 'GET_ALL_CATEGORY_SUCCESS',

 }


export const productConstants = {
 
    GET_PRODUCT_REQUEST :'GET_PRODUCT_REQUEST',
    GET_PRODUCT_FAILURE : 'GET_PRODUCT_FAILURE',
    GET_PRODUCT_SUCCESS : 'GET_PRODUCT_SUCCESS'

 }

 export const initialDataConstants = {
   INITIAL_DATA_REQUEST :'INITIAL_DATA_REQUEST',
   INITIAL_DATA_FAILURE : 'INITIAL_DATA_FAILURE',
   INITIAL_DATA_SUCCESS : 'INITIAL_DATA_SUCCESS',
 }
 export const cartConstants = {
  ADD_TO_CART_REQUEST :'ADD_TO_CART_REQUEST',
  ADD_TO_CART_FAILURE : 'ADD_TO_CART_FAILURE',
  ADD_TO_CART_SUCCESS : 'ADD_TO_CART_SUCCESS',
  GET_CART_ITEMS_REQUEST :'GET_CART_ITEMS_REQUEST',
  GET_CART_ITEMS_FAILURE : 'GET_CART_ITEMS_FAILURE',
  GET_CART_ITEMS_SUCCESS : 'GET_CART_ITEMS_SUCCESS',
  EMPTY_CART_ITEMS_REQUEST :'EMPTY_CART_ITEMS_REQUEST',
  EMPTY_CART_ITEMS_FAILURE : 'EMPTY_CART_ITEMS_FAILURE',
  EMPTY_CART_ITEMS_SUCCESS : 'EMPTY_CART_ITEMS_SUCCESS',
}

export const orderConstants = {
  ADD_TO_ORDER_REQUEST :'ADD_TO_ORDER_REQUEST',
  ADD_TO_ORDER_FAILURE : 'ADD_TO_ORDER_FAILURE',
  ADD_TO_ORDER_SUCCESS : 'ADD_TO_ORDER_SUCCESS',
  GET_ORDER_ITEMS_REQUEST :'GET_ORDER_ITEMS_REQUEST',
  GET_ORDER_ITEMS_FAILURE : 'GET_ORDER_ITEMS_FAILURE',
  GET_ORDER_ITEMS_SUCCESS : 'GET_ORDER_ITEMS_SUCCESS',
}